### ISSUE TITLE
error

### ISSUE THREAD

**Issue by rydelek11** [mazk5145/Keyauth-Redeem-Bot#1]
hello , when i put wrong code bot crashed in line 39 index.js 
![obraz](https://user-images.githubusercontent.com/39122430/169426660-383a25c3-8eee-42a9-a555-153062e88d5c.png)
![obraz](https://user-images.githubusercontent.com/39122430/169426719-2b0385be-b709-41ad-904f-4ac52386e792.png)

**Comment by mazk5145** [comment]
you cannot use "message" on "interaction"
change `message.author` to `interaction.member.user`

**Comment by mazk5145** [comment]
and for getting user id: `interaction.member.user.id`

**Comment by rydelek11** [comment]
thxn !

**Comment by mazk5145** [comment]
Solved / Information have been provided.
